#import "~/graphql/user/authedUserFragment.gql"

mutation($username: String!, $password: String!, $passwordConfirm: String!){
  register (
      input: {
        username: $username
        password: $password
        password_confirmation: $passwordConfirm
      }
    ){
      access_token
      refresh_token
      expires_in
      token_type
      user {
        ...AuthedUserFragment
      }
    }
}
