#import "~/graphql/user/authedUserFragment.gql"

mutation(
  $id: ID!
  $username: String!
  $email: String
  $bio: String
){
  updateUser(input:{
    id: $id
    username: $username
    profile: {
      update: {
        user_id: $id
        email: $email
        bio: $bio
      }
    }
  }){
    ...AuthedUserFragment
  }
}