#import "~/graphql/user/authedUserFragment.gql"

mutation(
  $id: ID!
  $username: String!
  $email: String
  $bio: String
){
  updateUser(
    id: $id
    username: $username
    email: $email
    bio: $bio
  ){
    ...AuthedUserFragment
  }
}